name: Playwright Tests kp

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test
        continue-on-error: true

      - name: Upload Playwright HTML Report as artifact
        if: always()
        uses: actions/upload-artifact@v4

        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


      - name: Upload JUnit test results as artifact

      - name: Upload test results (JUnit)

        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
          retention-days: 7


      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
          force_orphan: true

      - name: Add Playwright report link to summary
        if: always()
        run: echo "👉 [View Playwright Report](https://your-username.github.io/your-repo-name/)" >> $GITHUB_STEP_SUMMARY

      - name: Send email with test artifacts and report link
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Playwright Test Artifacts and Results
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Hello,

            The Playwright test run has completed.

            👉 View HTML Report: https://Kpatil2912.github.io/Playwright-typescript-tests/

            Attached are the test artifacts for further review.

            Regards,  
            Kiran QA Team
          attachments: |
            playwright-report/
            test-results/

