name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify an exact LTS version instead of 'lts/*' for consistency
          cache: 'npm' # Cache npm dependencies to speed up future runs

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit # Use --prefer-offline to avoid network issues, --no-audit to skip audit for faster execution

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always() # Upload report even if tests fail, but not if the job is cancelled
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
